<template>
  <el-table
    :data="tableData"
    border
    style="width: 100%">
    <el-table-column
      prop="F0"
      label="F0">
    </el-table-column>
    <el-table-column
      prop="F1"
      label="F1">
    </el-table-column>
    <el-table-column
      prop="F2"
      label="F2">
    </el-table-column>
    <el-table-column
      prop="F3"
      label="F3">
    </el-table-column>
    <el-table-column
      prop="F4"
      label="F4">
    </el-table-column>
    <el-table-column
      prop="F5"
      label="F5">
    </el-table-column>
    <el-table-column
      prop="F6"
      label="F6">
    </el-table-column>
    <el-table-column
      prop="F7"
      label="F7">
    </el-table-column>
    <el-table-column
      prop="F8"
      label="F8">
    </el-table-column>
    <el-table-column
      prop="F9"
      label="F9">
    </el-table-column>
    <el-table-column
      prop="F10"
      label="F10">
    </el-table-column>
    <el-table-column
      prop="F11"
      label="F11">
    </el-table-column>
  </el-table>
</template>

<script>
  export default {
    data() {
      return {
        tableData: [{
          F0:"",
          F1:"",
          F2:"Integer",
          F3:"",
          F4:"",
          F5:"",
          F6:"",
          F7:"",
          F8:"",
          F9:"",
          F10:"",
          F11:""
        }
        ]
      }
    }
  }
</script>